#!/usr/bin/env bash

#VARIABLES DEFINITION

nome=$1
email=$2

#SETTING THE GLOBAL CONFIGS

$(git config --global user.name "$nome")
$(git config --global user.email "$email")
$(git config --global init.defaultBranch main)
$(git config --global --list)

#SSH AUTH

$(ssh-keygen -t ed25519 -C "$email")
$(eval"$(ssh-agent -s)")
$(ssh-add ~/.ssh/id_ed25519)

cat ~/.ssh/id_ed25519.pub
